language: cpp
 
os:
- linux
- osx
 
env:
  matrix:
    - NODE_VERSION="10.15"
    - NODE_VERSION="8.6"
    - NODE_VERSION="6.11"
    - NODE_VERSION="4.4"
  include:
    - os: osx
      osx_image: xcode8.3
 
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install fontconfig ; fi
- rm -rf ~/.nvm/ && git clone --depth 1 https://github.com/creationix/nvm.git ~/.nvm
- source ~/.nvm/nvm.sh
- nvm install $NODE_VERSION
- nvm use $NODE_VERSION
# Upgrade npm
# - npm install -g npm
- npm install -g node-pre-gyp 
- npm install -g node-pre-gyp-github
- git config --global credential.helper store
- git config --global github.token $NODE_PRE_GYP_GITHUB_TOKEN
- git config --global user.email "matthias.dieudonne@gmail.com"
- git config --global user.name "MatthD"

install:
# - npm install --build-from-source
- npm i nan
- node-pre-gyp configure --enable-build-type=release
- node-pre-gyp build
- node-pre-gyp package

script:
- |
  PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
  RELEASE_VERSION=$(curl --silent "https://api.github.com/repos/$1/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")')
  if [ "$PACKAGE_VERSION" = "$RELEASE_VERSION" ]
  then
    echo "Version PACKAGE_VERSION already released
  else
    node-pre-gyp-github publish
  fi
 
notifications:
  email: false
